"""PDF Report Generator using ReportLab Platypus."""

import os
from datetime import datetime
from typing import Optional
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, ListFlowable, ListItem, Image
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY


class ReportGenerator:
    """Generate PDF reports for research groups."""
    
    REPORTS_DIR = os.environ.get("REPORTS_DIR", "/app/reports")  # Docker path with fallback
    
    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir or self.REPORTS_DIR
        # Only create directory if it's accessible
        try:
            os.makedirs(self.output_dir, exist_ok=True)
        except PermissionError:
            # Fallback to temp directory for local dev/testing
            import tempfile
            self.output_dir = os.path.join(tempfile.gettempdir(), "openresearch_reports")
            os.makedirs(self.output_dir, exist_ok=True)
        
        # Setup styles
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()
    
    def _add_custom_styles(self):
        """Add custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1a365d')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionTitle',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#2c5282')
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubSection',
            parent=self.styles['Heading3'],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=colors.HexColor('#4a5568')
        ))
        
        # Override existing BodyText style instead of adding
        self.styles['BodyText'].fontSize = 10
        self.styles['BodyText'].leading = 14
        self.styles['BodyText'].alignment = TA_JUSTIFY
        self.styles['BodyText'].spaceAfter = 8
        
        self.styles.add(ParagraphStyle(
            name='Quote',
            parent=self.styles['Normal'],
            fontSize=10,
            leftIndent=20,
            rightIndent=20,
            fontName='Helvetica-Oblique',
            textColor=colors.HexColor('#4a5568'),
            spaceBefore=10,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            alignment=TA_CENTER
        ))
    
    def generate_group_report(
        self,
        group_id: str,
        group_name: str,
        group_description: str,
        sessions: list[dict],
        papers: list[dict],
        summaries: list[dict],
        qa_artifacts: list[dict],
        memory_notes: list[dict],
        generated_by: str,
        include_sessions: bool = True,
        include_papers: bool = True,
        include_summaries: bool = True,
        custom_prompt: Optional[str] = None
    ) -> tuple[str, str, int]:
        """
        Generate a comprehensive group report PDF.
        
        Returns:
            Tuple of (file_path, filename, file_size)
        """
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"openresearch-report-{group_id[:8]}-{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        # Create document
        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        # Build content
        story = []
        
        # Title Page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("OpenResearch", self.styles['ReportTitle']))
        story.append(Paragraph("Group Research Report", self.styles['SectionTitle']))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(f"<b>{group_name}</b>", self.styles['Heading2']))
        story.append(Paragraph(group_description, self.styles['BodyText']))
        story.append(Spacer(1, inch))
        
        # Report metadata
        meta_data = [
            ["Generated", datetime.now().strftime("%B %d, %Y at %H:%M")],
            ["Generated By", generated_by],
            ["Group ID", group_id[:8] + "..."],
            ["Total Sessions", str(len(sessions))],
            ["Total Papers", str(len(papers))],
            ["AI Summaries", str(len(summaries))],
        ]
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#2c5282')),
        ]))
        story.append(meta_table)
        story.append(PageBreak())
        
        # Table of Contents
        story.append(Paragraph("Table of Contents", self.styles['SectionTitle']))
        toc_items = ["1. Executive Summary"]
        if include_papers:
            toc_items.append("2. Research Papers")
        if include_sessions:
            toc_items.append(f"{len(toc_items)+1}. Discussion Sessions")
        if include_summaries:
            toc_items.append(f"{len(toc_items)+1}. AI-Generated Summaries")
        toc_items.append(f"{len(toc_items)+1}. Q&A Artifacts")
        if memory_notes:
            toc_items.append(f"{len(toc_items)+1}. Group Memory Notes")
        
        for item in toc_items:
            story.append(Paragraph(item, self.styles['BodyText']))
        story.append(PageBreak())
        
        # Executive Summary
        story.append(Paragraph("1. Executive Summary", self.styles['SectionTitle']))
        exec_summary = f"""
        This report compiles research activities from the group "{group_name}". 
        The group has conducted {len(sessions)} discussion sessions, 
        analyzed {len(papers)} research papers, and generated {len(summaries)} AI-powered summaries.
        """
        story.append(Paragraph(exec_summary, self.styles['BodyText']))
        
        if custom_prompt:
            story.append(Paragraph("Custom Analysis Request:", self.styles['SubSection']))
            story.append(Paragraph(custom_prompt.replace('@ai', '').strip(), self.styles['Quote']))
        
        story.append(Spacer(1, 0.3*inch))
        
        section_num = 2
        
        # Research Papers Section
        if include_papers and papers:
            story.append(Paragraph(f"{section_num}. Research Papers", self.styles['SectionTitle']))
            story.append(Paragraph(
                f"The group has collected and analyzed {len(papers)} research papers.",
                self.styles['BodyText']
            ))
            
            for i, paper in enumerate(papers, 1):
                story.append(Paragraph(
                    f"{section_num}.{i} {paper.get('title', 'Untitled')}",
                    self.styles['SubSection']
                ))
                
                # Paper metadata
                authors = paper.get('authors', [])
                if authors:
                    authors_str = ", ".join(authors[:3])
                    if len(authors) > 3:
                        authors_str += f" et al. ({len(authors)} authors)"
                    story.append(Paragraph(f"<b>Authors:</b> {authors_str}", self.styles['BodyText']))
                
                if paper.get('published_date'):
                    story.append(Paragraph(
                        f"<b>Published:</b> {paper['published_date']}",
                        self.styles['BodyText']
                    ))
                
                if paper.get('tags'):
                    tags_str = ", ".join(paper['tags'][:5])
                    story.append(Paragraph(f"<b>Tags:</b> {tags_str}", self.styles['BodyText']))
                
                abstract = paper.get('abstract', '')
                if abstract:
                    story.append(Paragraph("<b>Abstract:</b>", self.styles['BodyText']))
                    # Truncate long abstracts
                    if len(abstract) > 500:
                        abstract = abstract[:500] + "..."
                    story.append(Paragraph(abstract, self.styles['Quote']))
                
                story.append(Spacer(1, 0.2*inch))
            
            section_num += 1
            story.append(PageBreak())
        
        # Discussion Sessions Section
        if include_sessions and sessions:
            story.append(Paragraph(f"{section_num}. Discussion Sessions", self.styles['SectionTitle']))
            
            for i, session in enumerate(sessions, 1):
                story.append(Paragraph(
                    f"{section_num}.{i} {session.get('title', 'Untitled Session')}",
                    self.styles['SubSection']
                ))
                
                story.append(Paragraph(
                    f"<b>Status:</b> {session.get('status', 'active')} | "
                    f"<b>Created:</b> {session.get('created_at', 'Unknown')[:10] if session.get('created_at') else 'Unknown'}",
                    self.styles['BodyText']
                ))
                
                messages = session.get('messages', [])
                if messages:
                    story.append(Paragraph(
                        f"<b>Messages:</b> {len(messages)} total",
                        self.styles['BodyText']
                    ))
                    
                    # Show first few messages
                    for msg in messages[:5]:
                        sender = msg.get('user_name', 'Unknown')
                        content = msg.get('content', '')[:200]
                        if len(msg.get('content', '')) > 200:
                            content += "..."
                        story.append(Paragraph(
                            f"<b>{sender}:</b> {content}",
                            self.styles['Quote']
                        ))
                    
                    if len(messages) > 5:
                        story.append(Paragraph(
                            f"... and {len(messages) - 5} more messages",
                            self.styles['BodyText']
                        ))
                
                story.append(Spacer(1, 0.2*inch))
            
            section_num += 1
            story.append(PageBreak())
        
        # AI Summaries Section
        if include_summaries and summaries:
            story.append(Paragraph(f"{section_num}. AI-Generated Summaries", self.styles['SectionTitle']))
            
            for i, summary in enumerate(summaries, 1):
                story.append(Paragraph(
                    f"{section_num}.{i} Summary",
                    self.styles['SubSection']
                ))
                
                story.append(Paragraph(
                    f"<b>Type:</b> {summary.get('artifact_type', 'summary')} | "
                    f"<b>Created:</b> {summary.get('created_at', 'Unknown')[:10] if summary.get('created_at') else 'Unknown'}",
                    self.styles['BodyText']
                ))
                
                content = summary.get('content', '')
                if len(content) > 1000:
                    content = content[:1000] + "..."
                story.append(Paragraph(content, self.styles['Quote']))
                story.append(Spacer(1, 0.2*inch))
            
            section_num += 1
        
        # Q&A Artifacts Section
        if qa_artifacts:
            story.append(Paragraph(f"{section_num}. Q&A Artifacts", self.styles['SectionTitle']))
            
            for i, qa in enumerate(qa_artifacts, 1):
                story.append(Paragraph(f"{section_num}.{i} Q&A", self.styles['SubSection']))
                
                if qa.get('prompt'):
                    story.append(Paragraph(
                        f"<b>Question:</b> {qa['prompt'][:300]}",
                        self.styles['BodyText']
                    ))
                
                answer = qa.get('content', '')[:500]
                if len(qa.get('content', '')) > 500:
                    answer += "..."
                story.append(Paragraph(f"<b>Answer:</b>", self.styles['BodyText']))
                story.append(Paragraph(answer, self.styles['Quote']))
                story.append(Spacer(1, 0.1*inch))
            
            section_num += 1
        
        # Memory Notes Section
        if memory_notes:
            story.append(PageBreak())
            story.append(Paragraph(f"{section_num}. Group Memory Notes", self.styles['SectionTitle']))
            
            for note in memory_notes:
                note_type = note.get('note_type', 'note')
                story.append(Paragraph(
                    f"<b>[{note_type.upper()}]</b> {note.get('content', '')}",
                    self.styles['BodyText']
                ))
            
            section_num += 1
        
        # Footer
        story.append(Spacer(1, inch))
        story.append(Paragraph(
            "Generated by OpenResearch AI Platform",
            self.styles['Footer']
        ))
        story.append(Paragraph(
            f"Report ID: {group_id[:8]}-{timestamp}",
            self.styles['Footer']
        ))
        
        # Build PDF
        doc.build(story)
        
        # Get file size
        file_size = os.path.getsize(filepath)
        
        return filepath, filename, file_size
    
    def generate_sample_report(self) -> tuple[str, str, int]:
        """Generate a sample report for testing."""
        return self.generate_group_report(
            group_id="sample-group-id-12345678",
            group_name="Sample Research Group",
            group_description="A demonstration group for testing the report generation system.",
            sessions=[
                {
                    "title": "Initial Planning Session",
                    "status": "active",
                    "created_at": "2026-01-07T10:00:00Z",
                    "messages": [
                        {"user_name": "Alice", "content": "Let's discuss our research objectives for this quarter."},
                        {"user_name": "Bob", "content": "I think we should focus on transformer architectures."},
                        {"user_name": "AI Assistant", "content": "Based on recent papers, transformer architectures show promising results in various domains."},
                    ]
                }
            ],
            papers=[
                {
                    "title": "Attention Is All You Need",
                    "authors": ["Vaswani, A.", "Shazeer, N.", "Parmar, N."],
                    "published_date": "2017-06-12",
                    "tags": ["transformers", "attention", "nlp"],
                    "abstract": "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks."
                }
            ],
            summaries=[
                {
                    "artifact_type": "session_summary",
                    "created_at": "2026-01-07T12:00:00Z",
                    "content": "The team discussed research priorities focusing on transformer architectures and their applications."
                }
            ],
            qa_artifacts=[
                {
                    "prompt": "@ai What are the key innovations in the attention mechanism?",
                    "content": "The key innovations include multi-head attention, scaled dot-product attention, and positional encoding."
                }
            ],
            memory_notes=[
                {"note_type": "decision", "content": "Focus on transformer-based models for Q1 2026."},
                {"note_type": "guideline", "content": "All papers must be reviewed by at least two team members."}
            ],
            generated_by="System"
        )


# Singleton instance
report_generator = ReportGenerator()
